### ISSUE TITLE
Find a bug in the indev+ stable rev.20240331

### ISSUE THREAD

**Issue by Yuenjing1005** [VesuviusVenox/Legacy-Plus-Archive#3]
the pulley ( golden or iron one) is not working if world height is higher than 256 :(

**Comment by VesuviusVenox** [comment]
fixed and reuploaded

**Comment by Yuenjing1005** [comment]
> fixed and reuploaded

![2024-05-02_07 44 46](https://github.com/VesuviusVenox/Legacy-Plus-Archive/assets/102344371/0e668a44-6507-4ff3-8787-022a02143077)
sorry, but it seems not fixed, the pulley is still no reaction with my right clicking

**Comment by VesuviusVenox** [comment]
Did you get the jar from this repo? I don't upload to betacraft anymore, use multimc.

**Comment by Yuenjing1005** [comment]
> Did you get the jar from this repo? I don't upload to betacraft anymore, use multimc.

yes I downloaded the new jar. and use MultiMC aswell :(
![image](https://github.com/VesuviusVenox/Legacy-Plus-Archive/assets/102344371/48d93a52-3041-4882-864e-296b4ef4335a)
![image](https://github.com/VesuviusVenox/Legacy-Plus-Archive/assets/102344371/53c38c64-cd70-4769-b0fb-1572a4dad6c2)

**Comment by Yuenjing1005** [comment]
I have tested it in 1024 height and 512 height world but both world are not working.

**Comment by VesuviusVenox** [comment]
Reuploaded again, either my IDE failed to save for some reason, or I missed a piece of code.

**Comment by VesuviusVenox** [comment]
Can confirm it works on my end

**Comment by Yuenjing1005** [comment]
thank you so much for your effort :) I love this mod!
